# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql # empty data directory to execute SQL scripts
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hackathon
    ports:
      - 5000:3306
